// Programme Management Data
// Matching reference image: Ormiston Rise (Building 2 & Unit 80)
// ===============================================================

import type {
  ProgrammeTask,
  ProgrammeData,
  ProgrammeVersion,
  TaskStatus,
  Trade,
} from "./programme-types";

// ─── Reference Tasks Data ───────────────────────────────────────

export const INITIAL_PROGRAMME_TASKS: ProgrammeTask[] = [
  // Major Group 1: Site Establishment (matching reference image)
  {
    id: "task-site-est",
    wbs: "1.0",
    name: "Site Establishment",
    level: "phase",
    parentId: null,
    status: "complete",
    startDate: "2025-09-01",
    endDate: "2025-09-15",
    displayStart: "01 Sep 25",
    displayEnd: "15 Sep 25",
    duration: 15,
    progress: 100,
    trade: null,
    costCode: "PRE-00",
    assignee: null,
    assigneeInitials: "",
    description: "Site setup, boundary hoarding, welfare facilities, and temporary services connection.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: ["task-earthworks"],
    notes: "Site establishment fully signed off and handed over.",
    children: [
      "task-1-1-1", "task-1-1-2", "task-1-1-3", "task-1-1-4", "task-1-1-5",
      "task-1-1-6", "task-1-1-7", "task-1-1-8", "task-1-1-9", "task-1-1-10",
      "task-1-1-11", "task-1-1-12", "task-1-1-13"
    ],
    depth: 0,
    taskCount: 8,
    float: 0,
    iconType: "establishment",
  },
  // Task 1.1.1: Site possession
  {
    id: "task-1-1-1",
    wbs: "1.1.1",
    name: "Site possession",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-03-03",
    endDate: "2025-03-03",
    displayStart: "03 Mar 2025",
    displayEnd: "03 Mar 2025",
    duration: 0,
    progress: 100,
    trade: "Management",
    costCode: "PRE-01",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Formal handover and possession of site boundary from client.",
    isCritical: true,
    isMilestone: true,
    predecessors: [],
    successors: ["task-1-1-2"],
    notes: "Site possession certificate signed.",
    children: [],
    depth: 2,
    float: 0,
  },
  // Task 1.1.2: Hoarding and site signage installation
  {
    id: "task-1-1-2",
    wbs: "1.1.2",
    name: "Hoarding and site signage installation",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-03-03",
    endDate: "2025-03-10",
    displayStart: "03 Mar 2025",
    displayEnd: "10 Mar 2025",
    duration: 5,
    progress: 100,
    trade: "Civils",
    costCode: "PRE-02",
    assignee: "Paul Turner",
    assigneeInitials: "PT",
    description: "Erect 2.4m timber perimeter hoarding with viewing panels and site safety signage.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-1"],
    successors: ["task-1-1-3"],
    notes: "Hoarding licensed by local authority.",
    children: [],
    depth: 2,
    float: 2,
  },
  // Task 1.1.3: Temporary services connection
  {
    id: "task-1-1-3",
    wbs: "1.1.3",
    name: "Temporary services connection",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-03-06",
    endDate: "2025-03-18",
    displayStart: "06 Mar 2025",
    displayEnd: "18 Mar 2025",
    duration: 8,
    progress: 100,
    trade: "M&E",
    costCode: "PRE-03",
    assignee: "Sarah Carter",
    assigneeInitials: "SC",
    description: "Connection of temporary water supply, builder's electrical supply and drainage outfall.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-2"],
    successors: ["task-1-1-4"],
    notes: "Meters installed and certified.",
    children: [],
    depth: 2,
    float: 3,
  },
  // Task 1.1.4: Site welfare setup
  {
    id: "task-1-1-4",
    wbs: "1.1.4",
    name: "Site welfare setup",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-03-13",
    endDate: "2025-03-20",
    displayStart: "13 Mar 2025",
    displayEnd: "20 Mar 2025",
    duration: 5,
    progress: 100,
    trade: "Management",
    costCode: "PRE-04",
    assignee: "Mike Johnson",
    assigneeInitials: "MJ",
    description: "Delivery, double-stacking and plumbing of canteen, drying room, toilets and meeting rooms.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-3"],
    successors: ["task-1-1-5"],
    notes: "HSE inspection passed.",
    children: [],
    depth: 2,
    float: 1,
  },
  // Task 1.1.5: Site compound and laydown areas
  {
    id: "task-1-1-5",
    wbs: "1.1.5",
    name: "Site compound and laydown areas",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-03-18",
    endDate: "2025-03-27",
    displayStart: "18 Mar 2025",
    displayEnd: "27 Mar 2025",
    duration: 7,
    progress: 100,
    trade: "Civils",
    costCode: "PRE-05",
    assignee: "Paul Turner",
    assigneeInitials: "PT",
    description: "Install geotextile, hardcore base and tarmac surfacing for vehicle parking and steel laydown.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-4"],
    successors: ["task-1-1-6"],
    notes: "Laydown area demarcated.",
    children: [],
    depth: 2,
    float: 0,
  },
  // Task 1.1.6: Tower crane foundation
  {
    id: "task-1-1-6",
    wbs: "1.1.6",
    name: "Tower crane foundation",
    level: "task",
    parentId: "task-site-est",
    status: "in-progress",
    startDate: "2025-03-24",
    endDate: "2025-04-07",
    displayStart: "24 Mar 2025",
    displayEnd: "07 Apr 2025",
    duration: 10,
    progress: 70,
    trade: "Structural",
    costCode: "STR-01",
    assignee: "Ryan Wilson",
    assigneeInitials: "RW",
    description: "Excavate, cast rebar cage and pour 120m3 C50 concrete crane base with embedded fixing stools.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-1-1-5"],
    successors: ["task-1-1-7"],
    notes: "Cube compressive test achieved 55 MPa at 7 days.",
    children: [],
    depth: 2,
    float: 0,
  },
  // Task 1.1.7: Tower crane erection and commissioning
  {
    id: "task-1-1-7",
    wbs: "1.1.7",
    name: "Tower crane erection and commissioning",
    level: "task",
    parentId: "task-site-est",
    status: "in-progress",
    startDate: "2025-04-02",
    endDate: "2025-04-09",
    displayStart: "02 Apr 2025",
    displayEnd: "09 Apr 2025",
    duration: 5,
    progress: 55,
    trade: "Structural",
    costCode: "STR-02",
    assignee: "Ryan Wilson",
    assigneeInitials: "RW",
    description: "Mobile crane assisted erection of 55m jib tower crane, load calibration and handover certificate.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-1-1-6"],
    successors: ["task-1-1-8"],
    notes: "Appointed person signed off test lift.",
    children: [],
    depth: 2,
    float: 0,
  },
  // Task 1.1.8: Material hoist installation
  {
    id: "task-1-1-8",
    wbs: "1.1.8",
    name: "Material hoist installation",
    level: "task",
    parentId: "task-site-est",
    status: "not-started",
    startDate: "2025-04-07",
    endDate: "2025-04-11",
    displayStart: "07 Apr 2025",
    displayEnd: "11 Apr 2025",
    duration: 4,
    progress: 0,
    trade: "Structural",
    costCode: "STR-03",
    assignee: "Emma Collins",
    assigneeInitials: "EC",
    description: "Assemble twin-cage 2000kg goods hoist tied into external scaffold core.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-7"],
    successors: ["task-1-1-9"],
    notes: "Interlock gate testing complete.",
    children: [],
    depth: 2,
    float: 4,
  },
  // Task 1.1.9: Temporary access roads
  {
    id: "task-1-1-9",
    wbs: "1.1.9",
    name: "Temporary access roads",
    level: "task",
    parentId: "task-site-est",
    status: "not-started",
    startDate: "2025-04-09",
    endDate: "2025-04-17",
    displayStart: "09 Apr 2025",
    displayEnd: "17 Apr 2025",
    duration: 6,
    progress: 0,
    trade: "Civils",
    costCode: "EW-02",
    assignee: "Paul Turner",
    assigneeInitials: "PT",
    description: "Install one-way concrete haul road with wheel wash facility and traffic management signage.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-8"],
    successors: ["task-1-1-10"],
    notes: "Wheel wash drainage connected.",
    children: [],
    depth: 2,
    float: 2,
  },
  // Task 1.1.10: Environmental controls - silt fencing
  {
    id: "task-1-1-10",
    wbs: "1.1.10",
    name: "Environmental controls - silt fencing",
    level: "task",
    parentId: "task-site-est",
    status: "not-started",
    startDate: "2025-04-15",
    endDate: "2025-04-18",
    displayStart: "15 Apr 2025",
    displayEnd: "18 Apr 2025",
    duration: 3,
    progress: 0,
    trade: "Civils",
    costCode: "ENV-01",
    assignee: "Sarah Carter",
    assigneeInitials: "SC",
    description: "Install sediment retention silt fences and straw bale check dams along watercourse perimeter.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-9"],
    successors: ["task-1-1-11"],
    notes: "EPA inspection passed.",
    children: [],
    depth: 2,
    float: 5,
  },
  // Task 1.1.11: Noise and vibration monitoring setup
  {
    id: "task-1-1-11",
    wbs: "1.1.11",
    name: "Noise and vibration monitoring setup",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-04-17",
    endDate: "2025-04-21",
    displayStart: "17 Apr 2025",
    displayEnd: "21 Apr 2025",
    duration: 2,
    progress: 100,
    trade: "Management",
    costCode: "ENV-02",
    assignee: "Mike Johnson",
    assigneeInitials: "MJ",
    description: "Deploy 4 no. solar-powered telemetric noise and seismograph vibration sensors on boundary walls.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-10"],
    successors: ["task-1-1-12"],
    notes: "Live cellular data logging active.",
    children: [],
    depth: 2,
    float: 3,
  },
  // Task 1.1.12: Existing services survey and diversion
  {
    id: "task-1-1-12",
    wbs: "1.1.12",
    name: "Existing services survey and diversion",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-04-18",
    endDate: "2025-05-02",
    displayStart: "18 Apr 2025",
    displayEnd: "02 May 2025",
    duration: 10,
    progress: 100,
    trade: "Civils",
    costCode: "UTL-01",
    assignee: "Paul Turner",
    assigneeInitials: "PT",
    description: "GPR survey and vacuum excavation to isolate and divert live 11kV cable and 150mm gas main.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-1-1-11"],
    successors: ["task-1-1-13"],
    notes: "Utility company signed off connection.",
    children: [],
    depth: 2,
    float: 0,
  },
  // Task 1.1.13: Archaeological watching brief
  {
    id: "task-1-1-13",
    wbs: "1.1.13",
    name: "Archaeological watching brief",
    level: "task",
    parentId: "task-site-est",
    status: "complete",
    startDate: "2025-04-29",
    endDate: "2025-05-06",
    displayStart: "29 Apr 2025",
    displayEnd: "06 May 2025",
    duration: 5,
    progress: 100,
    trade: "Management",
    costCode: "ARC-01",
    assignee: "Emma Collins",
    assigneeInitials: "EC",
    description: "Continuous archaeologist monitoring of trial trenches and topsoil stripping across plot footprint.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-1-12"],
    successors: ["task-main-contractor-setup"],
    notes: "Archaeological report issued to city council.",
    children: [],
    depth: 2,
    float: 1,
  },
  // Subgroup 1.2: Main Contractor Setup (8 tasks)
  {
    id: "task-main-contractor-setup",
    wbs: "1.2",
    name: "Main Contractor Setup",
    level: "work-package",
    parentId: "task-enabling-works",
    status: "not-started",
    startDate: "2025-05-07",
    endDate: "2025-05-28",
    displayStart: "07 May 2025",
    displayEnd: "28 May 2025",
    duration: 15,
    progress: 0,
    trade: null,
    costCode: "PRE-MC",
    assignee: null,
    assigneeInitials: "",
    description: "Main contractor site management infrastructure and subcontractor inductions.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-site-est"],
    successors: ["task-earthworks"],
    notes: "Mobilisation scheduled post-welfare sign-off.",
    children: ["task-1-2-1", "task-1-2-2"],
    depth: 1,
    taskCount: 8,
    float: 5,
  },
  {
    id: "task-1-2-1",
    wbs: "1.2.1",
    name: "Main contractor office setup",
    level: "task",
    parentId: "task-main-contractor-setup",
    status: "not-started",
    startDate: "2025-05-07",
    endDate: "2025-05-18",
    displayStart: "07 May 2025",
    displayEnd: "18 May 2025",
    duration: 8,
    progress: 0,
    trade: "Management",
    costCode: "PRE-MC1",
    assignee: "David Wilson",
    assigneeInitials: "DW",
    description: "IT installation, desk layouts, safety boards and server setup.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: ["task-1-2-2"],
    notes: "Desks on order.",
    children: [],
    depth: 2,
    float: 5,
  },
  {
    id: "task-1-2-2",
    wbs: "1.2.2",
    name: "Subcontractor induction & access control",
    level: "task",
    parentId: "task-main-contractor-setup",
    status: "not-started",
    startDate: "2025-05-19",
    endDate: "2025-05-28",
    displayStart: "19 May 2025",
    displayEnd: "28 May 2025",
    duration: 7,
    progress: 0,
    trade: "Management",
    costCode: "PRE-MC2",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Biometric turnstiles and site induction briefing packages.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-1-2-1"],
    successors: [],
    notes: "Turnstiles delivery booked.",
    children: [],
    depth: 2,
    float: 5,
  },
  // Major Group 2: Earthworks
  {
    id: "task-earthworks",
    wbs: "2.0",
    name: "Earthworks",
    level: "phase",
    parentId: null,
    status: "in-progress",
    startDate: "2025-09-16",
    endDate: "2025-10-10",
    displayStart: "16 Sep 25",
    displayEnd: "10 Oct 25",
    duration: 19,
    progress: 82,
    trade: "Civils",
    costCode: "EW-01",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Bulk excavation, soil retention system, piling platform and trenching for underground utilities.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-site-est"],
    successors: ["task-superstructure"],
    notes: "Final trimming and retention piles in final inspection.",
    children: [],
    depth: 0,
    taskCount: 28,
    float: 0,
    iconType: "earthworks",
  },
  // Major Group 3: Superstructure (EXPANDED BY DEFAULT)
  {
    id: "task-superstructure",
    wbs: "3.0",
    name: "Superstructure",
    level: "phase",
    parentId: null,
    status: "in-progress",
    startDate: "2025-10-11",
    endDate: "2026-03-20",
    displayStart: "11 Oct 25",
    displayEnd: "20 Mar 26",
    duration: 115,
    progress: 68,
    trade: "Structural",
    costCode: "STR-00",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Reinforced concrete frame, post-tensioned slabs, shear walls, columns and structural stair cores.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-earthworks"],
    successors: ["task-facade"],
    notes: "Level 1 complete. Level 2 concrete columns underway.",
    children: ["task-level-1", "task-level-2", "task-level-3", "task-level-4"],
    depth: 0,
    taskCount: 120,
    float: 0,
    iconType: "building",
  },
  // Subgroup 3.1: Level 1
  {
    id: "task-level-1",
    wbs: "3.1",
    name: "Level 1",
    level: "work-package",
    parentId: "task-superstructure",
    status: "complete",
    startDate: "2025-10-11",
    endDate: "2025-12-19",
    displayStart: "11 Oct 25",
    displayEnd: "19 Dec 25",
    duration: 50,
    progress: 100,
    trade: "Structural",
    costCode: "STR-L1",
    assignee: "Michael O'Brien",
    assigneeInitials: "MO",
    description: "Level 1 structural deck, columns, shear walls, and post-tensioned slab pour.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-earthworks"],
    successors: ["task-level-2"],
    notes: "Level 1 slab signed off and cured.",
    children: [],
    depth: 1,
    taskCount: 28,
    float: 0,
    iconType: "floor",
  },
  // Subgroup 3.2: Level 2 (EXPANDED BY DEFAULT)
  {
    id: "task-level-2",
    wbs: "3.2",
    name: "Level 2",
    level: "work-package",
    parentId: "task-superstructure",
    status: "in-progress",
    startDate: "2025-12-20",
    endDate: "2026-02-28",
    displayStart: "20 Dec 25",
    displayEnd: "28 Feb 26",
    duration: 50,
    progress: 46,
    trade: "Structural",
    costCode: "STR-L2",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Level 2 vertical structure: columns, perimeter blockwork, formwork and suspended slab.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-level-1"],
    successors: ["task-level-3"],
    notes: "Columns 60% poured. Blockwork staging started.",
    children: ["task-columns", "task-blockwork", "task-slab"],
    depth: 1,
    taskCount: 32,
    float: 0,
    iconType: "floor",
  },
  // Task 3.2.1: Columns (SELECTED IN REFERENCE DEMO)
  {
    id: "task-columns",
    wbs: "3.2.1",
    name: "Columns",
    level: "task",
    parentId: "task-level-2",
    status: "in-progress",
    startDate: "2025-12-20",
    endDate: "2026-01-16",
    displayStart: "20 Dec 25",
    displayEnd: "16 Jan 26",
    duration: 12,
    progress: 60,
    trade: "Concrete",
    costCode: "STR-CL-02",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Reinforced concrete columns to Level 2 as per structural drawings.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-level-1-slab"],
    successors: ["task-blockwork"],
    predecessorDetails: [
      {
        id: "task-level-1-slab",
        name: "Level 1 Slab Completion",
        relation: "Finishes before this starts (FS)",
        statusColor: "emerald",
      },
    ],
    successorDetails: [
      {
        id: "task-blockwork",
        name: "Level 2 Blockwork",
        relation: "Starts after this finishes (FS)",
        statusColor: "gray",
      },
    ],
    notes: "Pours 1 through 4 completed and tested at 32MPa. Pours 5 & 6 formwork in position.",
    children: [
      "task-due-1",
      "task-due-2",
      "task-due-3",
      "task-blocked-3",
      "task-due-7",
      "task-due-9",
      "task-due-11",
    ],
    depth: 2,
    taskCount: 8,
    float: 0,
    iconType: "columns",
  },
  // Task 3.2.2: Blockwork
  {
    id: "task-blockwork",
    wbs: "3.2.2",
    name: "Blockwork",
    level: "task",
    parentId: "task-level-2",
    status: "in-progress",
    startDate: "2026-01-17",
    endDate: "2026-02-06",
    displayStart: "17 Jan 26",
    displayEnd: "06 Feb 26",
    duration: 15,
    progress: 25,
    trade: "Concrete",
    costCode: "STR-BW-02",
    assignee: "Sarah Chen",
    assigneeInitials: "SC",
    description: "Acoustic core blockwork and fire separation walls on Level 2 perimeter.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-columns"],
    successors: ["task-slab"],
    predecessorDetails: [
      {
        id: "task-columns",
        name: "Level 2 Columns",
        relation: "Finishes before this starts (FS)",
        statusColor: "blue",
      },
    ],
    successorDetails: [
      {
        id: "task-slab",
        name: "Level 2 Slab",
        relation: "Starts after this finishes (FS)",
        statusColor: "gray",
      },
    ],
    notes: "Mortar testing passed. First lift completed on north wing.",
    children: [],
    depth: 2,
    taskCount: 12,
    float: 3,
    iconType: "blockwork",
  },
  // Task 3.2.3: Slab
  {
    id: "task-slab",
    wbs: "3.2.3",
    name: "Slab",
    level: "task",
    parentId: "task-level-2",
    status: "not-started",
    startDate: "2026-02-07",
    endDate: "2026-02-28",
    displayStart: "07 Feb 26",
    displayEnd: "28 Feb 26",
    duration: 16,
    progress: 0,
    trade: "Concrete",
    costCode: "STR-SL-02",
    assignee: "Michael O'Brien",
    assigneeInitials: "MO",
    description: "Formwork, tendon placement, rebar reinforcement and post-tensioned concrete pour for Level 2 slab.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-blockwork"],
    successors: ["task-level-3"],
    predecessorDetails: [
      {
        id: "task-blockwork",
        name: "Level 2 Blockwork",
        relation: "Finishes before this starts (FS)",
        statusColor: "blue",
      },
    ],
    successorDetails: [
      {
        id: "task-level-3",
        name: "Level 3 Structure",
        relation: "Starts after this finishes (FS)",
        statusColor: "gray",
      },
    ],
    notes: "Tendon delivery scheduled for 3 Feb 2026.",
    children: [],
    depth: 2,
    taskCount: 12,
    float: 0,
    iconType: "slab",
  },
  // Subgroup 3.3: Level 3
  {
    id: "task-level-3",
    wbs: "3.3",
    name: "Level 3",
    level: "work-package",
    parentId: "task-superstructure",
    status: "not-started",
    startDate: "2026-03-01",
    endDate: "2026-05-15",
    displayStart: "01 Mar 26",
    displayEnd: "15 May 26",
    duration: 55,
    progress: 0,
    trade: "Structural",
    costCode: "STR-L3",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Level 3 vertical framing, columns and concrete slab.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-level-2"],
    successors: ["task-level-4"],
    notes: "Milestone: Level 3 Complete due 16 Apr 2026.",
    children: [],
    depth: 1,
    taskCount: 30,
    float: 0,
    iconType: "floor",
  },
  // Subgroup 3.4: Level 4
  {
    id: "task-level-4",
    wbs: "3.4",
    name: "Level 4",
    level: "work-package",
    parentId: "task-superstructure",
    status: "not-started",
    startDate: "2026-05-16",
    endDate: "2026-07-20",
    displayStart: "16 May 26",
    displayEnd: "20 Jul 26",
    duration: 45,
    progress: 0,
    trade: "Structural",
    costCode: "STR-L4",
    assignee: "Michael O'Brien",
    assigneeInitials: "MO",
    description: "Level 4 roof deck and plant room structure.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["task-level-3"],
    successors: ["task-completion"],
    notes: "Pending structural engineer review.",
    children: [],
    depth: 1,
    taskCount: 30,
    float: 0,
    iconType: "floor",
  },
  // Major Group 4: Façade
  {
    id: "task-facade",
    wbs: "4.0",
    name: "Façade",
    level: "phase",
    parentId: null,
    status: "in-progress",
    startDate: "2026-03-21",
    endDate: "2026-06-30",
    displayStart: "21 Mar 26",
    displayEnd: "30 Jun 26",
    duration: 72,
    progress: 34,
    trade: "Envelope",
    costCode: "ENV-01",
    assignee: "Sarah Chen",
    assigneeInitials: "SC",
    description: "Unitised curtain wall, glazing panels, aluminium composite cladding, insulation and weather seals.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-superstructure"],
    successors: ["task-fitout"],
    notes: "Extrusions delivered to site. Bracket installation active.",
    children: [],
    depth: 0,
    taskCount: 64,
    float: 14,
    iconType: "facade",
  },
  // Major Group 5: Fitout
  {
    id: "task-fitout",
    wbs: "5.0",
    name: "Fitout",
    level: "phase",
    parentId: null,
    status: "not-started",
    startDate: "2026-04-01",
    endDate: "2026-09-15",
    displayStart: "01 Apr 26",
    displayEnd: "15 Sep 26",
    duration: 120,
    progress: 0,
    trade: "Finishes",
    costCode: "FIT-01",
    assignee: "Emma Thompson",
    assigneeInitials: "ET",
    description: "Internal stud partitions, ceilings, electrical rough-in, joinery, floor finishes, sanitaryware and decorating.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-facade"],
    successors: ["task-completion"],
    notes: "First fix M&E coordination drawings approved.",
    children: [],
    depth: 0,
    taskCount: 180,
    float: 8,
    iconType: "fitout",
  },
  // Major Group 6: External Works
  {
    id: "task-external-works",
    wbs: "6.0",
    name: "External Works",
    level: "phase",
    parentId: null,
    status: "not-started",
    startDate: "2026-09-16",
    endDate: "2026-10-31",
    displayStart: "16 Sep 26",
    displayEnd: "31 Oct 26",
    duration: 33,
    progress: 0,
    trade: "External Works",
    costCode: "EXT-01",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Paving, kerbing, asphalt access roads, drainage attenuation pond, boundary fencing and soft landscaping.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["task-fitout"],
    successors: ["task-completion"],
    notes: "Council road opening permit lodged.",
    children: [],
    depth: 0,
    taskCount: 55,
    float: 12,
    iconType: "external",
  },
  // Major Group 7: Completion
  {
    id: "task-completion",
    wbs: "7.0",
    name: "Completion",
    level: "phase",
    parentId: null,
    status: "not-started",
    startDate: "2026-11-01",
    endDate: "2026-11-15",
    displayStart: "01 Nov 26",
    displayEnd: "15 Nov 26",
    duration: 11,
    progress: 0,
    trade: "Management",
    costCode: "CMP-01",
    assignee: "David Wilson",
    assigneeInitials: "DW",
    description: "Testing & commissioning, practical completion inspection, O&M manuals handover and building certification.",
    isCritical: true,
    isMilestone: true,
    predecessors: ["task-external-works"],
    successors: [],
    notes: "Handover target date: 15 Nov 2026.",
    children: [],
    depth: 0,
    taskCount: 24,
    float: 0,
    iconType: "completion",
  },
];

// Additional attention tasks (to satisfy 5 Overdue, 3 Blocked, 12 Due This Week filters)
export const ATTENTION_TASKS: ProgrammeTask[] = [
  // 5 Overdue Tasks
  {
    id: "task-overdue-1",
    wbs: "2.3.1",
    name: "Substation Cable Trenching",
    level: "task",
    parentId: "task-earthworks",
    status: "blocked",
    startDate: "2025-09-20",
    endDate: "2025-10-02",
    displayStart: "20 Sep 25",
    displayEnd: "02 Oct 25",
    duration: 10,
    progress: 45,
    trade: "M&E",
    costCode: "ELE-TR-01",
    assignee: "James Burke",
    assigneeInitials: "JB",
    description: "Excavation and ducting for primary 11kV electrical incoming supply cable.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Overdue by 8 days. Waiting for utility authority permit approval.",
    children: [],
    depth: 1,
    isOverdue: true,
    isBlocked: true,
    float: -8,
  },
  {
    id: "task-overdue-2",
    wbs: "2.4.2",
    name: "Stormwater Attenuation Tank Delivery",
    level: "task",
    parentId: "task-earthworks",
    status: "blocked",
    startDate: "2025-09-22",
    endDate: "2025-10-04",
    displayStart: "22 Sep 25",
    displayEnd: "04 Oct 25",
    duration: 10,
    progress: 30,
    trade: "Civils",
    costCode: "CIV-ST-02",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Precast stormwater tank modular components transport and site unloading.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Overdue by 6 days. Crane permit rescheduling required.",
    children: [],
    depth: 1,
    isOverdue: true,
    isBlocked: true,
    float: -6,
  },
  {
    id: "task-overdue-3",
    wbs: "3.1.8",
    name: "Level 1 Firestop Penetrations Inspection",
    level: "task",
    parentId: "task-level-1",
    status: "in-progress",
    startDate: "2025-10-01",
    endDate: "2025-10-08",
    displayStart: "01 Oct 25",
    displayEnd: "08 Oct 25",
    duration: 6,
    progress: 70,
    trade: "Envelope",
    costCode: "FIR-L1-01",
    assignee: "Priya Patel",
    assigneeInitials: "PP",
    description: "Third-party certifier inspection for fire collar penetrations on Level 1.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Overdue by 3 days. Re-inspection booked for tomorrow.",
    children: [],
    depth: 2,
    isOverdue: true,
    float: -3,
  },
  {
    id: "task-overdue-4",
    wbs: "3.1.9",
    name: "Level 1 Acoustic Seal Signoff",
    level: "task",
    parentId: "task-level-1",
    status: "in-progress",
    startDate: "2025-10-02",
    endDate: "2025-10-09",
    displayStart: "02 Oct 25",
    displayEnd: "09 Oct 25",
    duration: 5,
    progress: 60,
    trade: "Finishes",
    costCode: "ACO-L1-01",
    assignee: "Aisha Khan",
    assigneeInitials: "AK",
    description: "Field test certificate for acoustic partition seals between plant and residential zones.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Overdue by 2 days. Acoustic consultant attending Thursday.",
    children: [],
    depth: 2,
    isOverdue: true,
    float: -2,
  },
  {
    id: "task-overdue-5",
    wbs: "2.5.1",
    name: "Capping Beam Concrete Testing",
    level: "task",
    parentId: "task-earthworks",
    status: "in-progress",
    startDate: "2025-10-03",
    endDate: "2025-10-10",
    displayStart: "03 Oct 25",
    displayEnd: "10 Oct 25",
    duration: 5,
    progress: 50,
    trade: "Structural",
    costCode: "STR-CB-01",
    assignee: "John Murray",
    assigneeInitials: "JM",
    description: "Core compressive strength report for retaining wall capping beam.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Overdue by 1 day. Lab results pending dispatch.",
    children: [],
    depth: 1,
    isOverdue: true,
    float: -1,
  },

  // 3rd Blocked Task (in addition to overdue 1 & 2)
  {
    id: "task-blocked-3",
    wbs: "3.2.1.4",
    name: "Level 2 Lift Core Precast Embeds",
    level: "task",
    parentId: "task-columns",
    status: "blocked",
    startDate: "2025-12-28",
    endDate: "2026-01-10",
    displayStart: "28 Dec 25",
    displayEnd: "10 Jan 26",
    duration: 9,
    progress: 15,
    trade: "Structural",
    costCode: "STR-EM-02",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Steel structural embed plates for lift guide rails.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Fabricator drawing clarification RFI #104 pending response.",
    children: [],
    depth: 3,
    isBlocked: true,
    float: 4,
  },

  // 12 Due This Week Tasks
  {
    id: "task-due-1",
    wbs: "3.2.1.1",
    name: "Level 2 North Columns Formwork Stripping",
    level: "task",
    parentId: "task-columns",
    status: "in-progress",
    startDate: "2025-12-20",
    endDate: "2025-12-26",
    displayStart: "20 Dec 25",
    displayEnd: "26 Dec 25",
    duration: 6,
    progress: 80,
    trade: "Concrete",
    costCode: "STR-CL-02a",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Stripping and surface finishing of completed north columns.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Wednesday.",
    children: [],
    depth: 3,
    isDueThisWeek: true,
    float: 0,
  },
  {
    id: "task-due-2",
    wbs: "3.2.1.2",
    name: "Level 2 South Columns Rebar Tying",
    level: "task",
    parentId: "task-columns",
    status: "in-progress",
    startDate: "2025-12-27",
    endDate: "2026-01-02",
    displayStart: "27 Dec 25",
    displayEnd: "02 Jan 26",
    duration: 6,
    progress: 50,
    trade: "Concrete",
    costCode: "STR-CL-02b",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Fixing steel cages and starter bars for south columns.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Thursday.",
    children: [],
    depth: 3,
    isDueThisWeek: true,
    float: 0,
  },
  {
    id: "task-due-3",
    wbs: "3.2.1.3",
    name: "Level 2 South Columns Pour #4",
    level: "task",
    parentId: "task-columns",
    status: "not-started",
    startDate: "2026-01-03",
    endDate: "2026-01-07",
    displayStart: "03 Jan 26",
    displayEnd: "07 Jan 26",
    duration: 4,
    progress: 0,
    trade: "Concrete",
    costCode: "STR-CL-02c",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Concrete boom pump scheduled for 08:00 Friday morning.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Friday.",
    children: [],
    depth: 3,
    isDueThisWeek: true,
    float: 0,
  },
  {
    id: "task-due-4",
    wbs: "2.6.1",
    name: "Site Boundary Trench Backfilling",
    level: "task",
    parentId: "task-earthworks",
    status: "in-progress",
    startDate: "2025-10-12",
    endDate: "2025-10-16",
    displayStart: "12 Oct 25",
    displayEnd: "16 Oct 25",
    duration: 4,
    progress: 60,
    trade: "Civils",
    costCode: "CIV-BF-01",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Crushed rock backfill and compaction test along western boundary.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Thursday.",
    children: [],
    depth: 1,
    isDueThisWeek: true,
    float: 5,
  },
  {
    id: "task-due-5",
    wbs: "3.1.10",
    name: "Level 1 Mechanical Duct Penetration Sleeves",
    level: "task",
    parentId: "task-level-1",
    status: "in-progress",
    startDate: "2025-10-13",
    endDate: "2025-10-17",
    displayStart: "13 Oct 25",
    displayEnd: "17 Oct 25",
    duration: 4,
    progress: 75,
    trade: "M&E",
    costCode: "MEC-SL-01",
    assignee: "James Burke",
    assigneeInitials: "JB",
    description: "Galvanised duct sleeves through service risers.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Friday.",
    children: [],
    depth: 2,
    isDueThisWeek: true,
    float: 3,
  },
  {
    id: "task-due-6",
    wbs: "3.1.11",
    name: "Level 1 Hydraulic Waste Stack Pressure Testing",
    level: "task",
    parentId: "task-level-1",
    status: "not-started",
    startDate: "2025-10-15",
    endDate: "2025-10-17",
    displayStart: "15 Oct 25",
    displayEnd: "17 Oct 25",
    duration: 2,
    progress: 0,
    trade: "M&E",
    costCode: "PLM-PT-01",
    assignee: "James Burke",
    assigneeInitials: "JB",
    description: "Hydrostatic test on completed drainage stacks.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Friday.",
    children: [],
    depth: 2,
    isDueThisWeek: true,
    float: 4,
  },
  {
    id: "task-due-7",
    wbs: "3.2.1.5",
    name: "Level 2 Perimeter Scaffolding Lift 2",
    level: "task",
    parentId: "task-columns",
    status: "in-progress",
    startDate: "2026-01-08",
    endDate: "2026-01-12",
    displayStart: "08 Jan 26",
    displayEnd: "12 Jan 26",
    duration: 4,
    progress: 40,
    trade: "Management",
    costCode: "SCF-L2-01",
    assignee: "David Wilson",
    assigneeInitials: "DW",
    description: "External heavy-duty scaffolding erection for masonry trades.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Wednesday.",
    children: [],
    depth: 3,
    isDueThisWeek: true,
    float: 2,
  },
  {
    id: "task-due-8",
    wbs: "1.4.1",
    name: "Site Logistics Laydown Area Relocation",
    level: "task",
    parentId: "task-site-est",
    status: "in-progress",
    startDate: "2025-10-13",
    endDate: "2025-10-16",
    displayStart: "13 Oct 25",
    displayEnd: "16 Oct 25",
    duration: 3,
    progress: 60,
    trade: "Management",
    costCode: "LOG-02",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Repositioning steel rebar storage area for crane access.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Thursday.",
    children: [],
    depth: 1,
    isDueThisWeek: true,
    float: 7,
  },
  {
    id: "task-due-9",
    wbs: "3.2.1.6",
    name: "Level 2 Survey Setout Verification",
    level: "task",
    parentId: "task-columns",
    status: "not-started",
    startDate: "2026-01-13",
    endDate: "2026-01-15",
    displayStart: "13 Jan 26",
    displayEnd: "15 Jan 26",
    duration: 2,
    progress: 0,
    trade: "Civils",
    costCode: "SRV-L2-01",
    assignee: "Sarah Chen",
    assigneeInitials: "SC",
    description: "Laser grid layout check before blockwork commencement.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Wednesday.",
    children: [],
    depth: 3,
    isDueThisWeek: true,
    float: 0,
  },
  {
    id: "task-due-10",
    wbs: "2.7.1",
    name: "Underground Stormwater Pit C Interceptor",
    level: "task",
    parentId: "task-earthworks",
    status: "in-progress",
    startDate: "2025-10-12",
    endDate: "2025-10-16",
    displayStart: "12 Oct 25",
    displayEnd: "16 Oct 25",
    duration: 4,
    progress: 50,
    trade: "Civils",
    costCode: "CIV-PIT-03",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Oil and silt interceptor installation in Pit C.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Thursday.",
    children: [],
    depth: 1,
    isDueThisWeek: true,
    float: 6,
  },
  {
    id: "task-due-11",
    wbs: "3.2.1.7",
    name: "Level 2 Fire Protection Standpipe Extension",
    level: "task",
    parentId: "task-columns",
    status: "not-started",
    startDate: "2026-01-14",
    endDate: "2026-01-16",
    displayStart: "14 Jan 26",
    displayEnd: "16 Jan 26",
    duration: 2,
    progress: 0,
    trade: "M&E",
    costCode: "FIR-ST-02",
    assignee: "James Burke",
    assigneeInitials: "JB",
    description: "Temporary construction fire dry riser extension to Level 2 deck.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Friday.",
    children: [],
    depth: 2,
    isDueThisWeek: true,
    float: 0,
  },
  {
    id: "task-due-12",
    wbs: "1.5.1",
    name: "Site Environmental Compliance Audit",
    level: "task",
    parentId: "task-site-est",
    status: "not-started",
    startDate: "2025-10-17",
    endDate: "2025-10-17",
    displayStart: "17 Oct 25",
    displayEnd: "17 Oct 25",
    duration: 1,
    progress: 0,
    trade: "Management",
    costCode: "ENV-AUD-01",
    assignee: "Emma Thompson",
    assigneeInitials: "ET",
    description: "Monthly silt fencing, sediment basin and dust control formal review.",
    isCritical: false,
    isMilestone: false,
    predecessors: [],
    successors: [],
    notes: "Due Friday afternoon.",
    children: [],
    depth: 1,
    isDueThisWeek: true,
    float: 10,
  },
];

// Combine initial tasks
export const PRE_NETWORK_TASKS: ProgrammeTask[] = [
  ...INITIAL_PROGRAMME_TASKS,
  ...ATTENTION_TASKS,
];

// Reference programme metadata
export const PROGRAMME_DATA_INITIAL: ProgrammeData = {
  id: "prog-ormiston-rise",
  name: "Ormiston Rise",
  description: "Building 2 & Unit 80",
  versions: [
    {
      id: "ver-wf",
      name: "Working Forecast",
      state: "working-forecast",
      createdAt: "2025-08-15",
      isActive: true,
      isEditable: true,
    },
    {
      id: "ver-b0",
      name: "Baseline 0 (Contract)",
      state: "baseline-0",
      createdAt: "2025-06-01",
      isActive: false,
      isEditable: false,
    },
    {
      id: "ver-ab",
      name: "Approved Baseline 1.1",
      state: "approved-baseline",
      createdAt: "2025-07-20",
      isActive: false,
      isEditable: false,
    },
  ],
  activeVersion: {
    id: "ver-wf",
    name: "Working Forecast",
    state: "working-forecast",
    createdAt: "2025-08-15",
    isActive: true,
    isEditable: true,
  },
  tasks: PRE_NETWORK_TASKS,
  taskMap: new Map(PRE_NETWORK_TASKS.map((t) => [t.id, t])),
  phases: INITIAL_PROGRAMME_TASKS.filter((t) => t.level === "phase"),
  totalTasks: 817,
  completedTasks: 60,
  blockedTasks: 28,
  avgProgress: 48,
  startDate: "2025-09-01",
  endDate: "2026-06-30",
};

// ─── Network View Specific Tasks (Substructure Focus - 24 Tasks) ───

export const NETWORK_TASKS: ProgrammeTask[] = [
  // Stage: Piling (6 tasks)
  {
    id: "PRG-001",
    wbs: "3.1.1",
    name: "Site possession",
    level: "task",
    parentId: "wbs-3.1",
    status: "complete",
    startDate: "2025-10-15",
    endDate: "2025-10-15",
    displayStart: "15 Oct 25",
    displayEnd: "15 Oct 25",
    duration: 0,
    progress: 100,
    trade: "Management",
    costCode: "PRE-01",
    assignee: "David Wilson",
    assigneeInitials: "DW",
    description: "Formal handover of site and boundary possession certificate.",
    isCritical: true,
    isMilestone: true,
    predecessors: [],
    successors: ["PRG-010"],
    notes: "Site possession granted on 15 Oct.",
    children: [],
    depth: 2,
    stage: "Piling",
    stageColumn: "Piling",
    float: 0,
  },
  {
    id: "PRG-002",
    wbs: "3.1.2",
    name: "Site set up",
    level: "task",
    parentId: "wbs-3.1",
    status: "complete",
    startDate: "2025-10-16",
    endDate: "2025-10-21",
    displayStart: "16 Oct 25",
    displayEnd: "21 Oct 25",
    duration: 5,
    progress: 100,
    trade: "Management",
    costCode: "PRE-02",
    assignee: "David Wilson",
    assigneeInitials: "DW",
    description: "Setup welfare cabins, security fencing, temporary power and perimeter hoarding.",
    isCritical: true,
    isMilestone: false,
    predecessors: [],
    successors: ["PRG-010", "PRG-011", "PRG-020"],
    notes: "Set up signed off by HSE.",
    children: [],
    depth: 2,
    stage: "Piling",
    stageColumn: "Piling",
    float: 0,
  },
  {
    id: "PRG-010",
    wbs: "3.1.3",
    name: "Piling mat construction",
    level: "task",
    parentId: "wbs-3.1",
    status: "blocked",
    startDate: "2025-10-22",
    endDate: "2025-10-27",
    displayStart: "22 Oct 25",
    displayEnd: "27 Oct 25",
    duration: 5,
    progress: 0,
    trade: "Piling",
    costCode: "PIL-01",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Construct heavy duty engineered working platform for piling rig load capacity.",
    isCritical: true,
    isMilestone: false,
    isBlocked: true,
    blockedBy: "Unstable soft subgrade discovered in sector C",
    predecessors: ["PRG-001", "PRG-002"],
    successors: ["PRG-021"],
    predecessorDetails: [
      { id: "PRG-001", name: "PRG-001 Site possession", relation: "Finishes before this starts (FS)", statusColor: "emerald" },
      { id: "PRG-002", name: "PRG-002 Site set up", relation: "Finishes before this starts (FS)", statusColor: "emerald" }
    ],
    successorDetails: [
      { id: "PRG-021", name: "PRG-021 Ground improvement", relation: "Starts after this finishes (FS)", statusColor: "red" }
    ],
    notes: "Blocked due to CBR test results below 5%. Geotechnical engineer reviewing.",
    children: [],
    depth: 2,
    stage: "Piling",
    stageColumn: "Piling",
    float: -5,
  },
  {
    id: "PRG-011",
    wbs: "3.1.4",
    name: "CFA piling rig mobilisation",
    level: "task",
    parentId: "wbs-3.1",
    status: "complete",
    startDate: "2025-10-22",
    endDate: "2025-10-25",
    displayStart: "22 Oct 25",
    displayEnd: "25 Oct 25",
    duration: 3,
    progress: 100,
    trade: "Piling",
    costCode: "PIL-02",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Mobilisation of continuous flight auger rig, support cranes and auger tooling.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-002"],
    successors: ["PRG-012"],
    predecessorDetails: [
      { id: "PRG-002", name: "PRG-002 Site set up", relation: "Finishes before this starts (FS)", statusColor: "emerald" }
    ],
    successorDetails: [
      { id: "PRG-012", name: "PRG-012 CFA piling - Grid A-D", relation: "Starts after this finishes (FS)", statusColor: "blue" }
    ],
    notes: "Rig assembled on site.",
    children: [],
    depth: 2,
    stage: "Piling",
    stageColumn: "Piling",
    float: 8,
  },
  {
    id: "PRG-012",
    wbs: "3.1.5",
    name: "CFA piling - Grid A-D",
    level: "task",
    parentId: "wbs-3.1",
    status: "in-progress",
    startDate: "2025-10-26",
    endDate: "2025-11-08",
    displayStart: "26 Oct 25",
    displayEnd: "08 Nov 25",
    duration: 12,
    progress: 60,
    trade: "Piling",
    costCode: "PIL-03",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Drilling and concrete pumping for 48 no. 600mm diameter CFA piles along Grids A to D.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-011"],
    successors: ["PRG-013"],
    predecessorDetails: [
      { id: "PRG-011", name: "PRG-011 CFA piling rig mobilisation", relation: "Finishes before this starts (FS)", statusColor: "emerald" }
    ],
    successorDetails: [
      { id: "PRG-013", name: "PRG-013 Pile load testing", relation: "Starts after this finishes (FS)", statusColor: "gray" }
    ],
    notes: "29 of 48 piles completed.",
    children: [],
    depth: 2,
    stage: "Piling",
    stageColumn: "Piling",
    float: 6,
  },
  {
    id: "PRG-013",
    wbs: "3.1.6",
    name: "Pile load testing",
    level: "task",
    parentId: "wbs-3.1",
    status: "not-started",
    startDate: "2025-11-09",
    endDate: "2025-11-17",
    displayStart: "09 Nov 25",
    displayEnd: "17 Nov 25",
    duration: 8,
    progress: 0,
    trade: "Piling",
    costCode: "PIL-04",
    assignee: "Sarah Chen",
    assigneeInitials: "SC",
    description: "Static load test on 2 no. selected test piles up to 200% design working load.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-012"],
    successors: [],
    predecessorDetails: [
      { id: "PRG-012", name: "PRG-012 CFA piling - Grid A-D", relation: "Finishes before this starts (FS)", statusColor: "blue" }
    ],
    notes: "Testing equipment calibrated.",
    children: [],
    depth: 2,
    stage: "Piling",
    stageColumn: "Piling",
    float: 10,
  },

  // Stage: Groundworks (8 tasks)
  {
    id: "PRG-020",
    wbs: "3.2.1",
    name: "Excavation to formation",
    level: "task",
    parentId: "wbs-3.2",
    status: "complete",
    startDate: "2025-10-22",
    endDate: "2025-10-30",
    displayStart: "22 Oct 25",
    displayEnd: "30 Oct 25",
    duration: 8,
    progress: 100,
    trade: "Groundworks",
    costCode: "GW-01",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Bulk excavation down to basement formation level and spoil removal off-site.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["PRG-002"],
    successors: ["PRG-021"],
    notes: "Formation depth verified with GPS survey rover.",
    children: [],
    depth: 2,
    stage: "Groundworks",
    stageColumn: "Groundworks",
    float: 0,
  },
  {
    id: "PRG-021",
    wbs: "3.2.2",
    name: "Ground improvement - vibro stone columns",
    level: "task",
    parentId: "wbs-3.2",
    status: "blocked",
    startDate: "2025-11-12",
    endDate: "2025-12-03",
    displayStart: "12 Nov 2025",
    displayEnd: "03 Dec 2025",
    duration: 15,
    progress: 0,
    trade: "Groundworks",
    costCode: "STR-CL-01",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Vibro stone column installation to improve ground bearing capacity as per geotechnical recommendations.",
    isCritical: true,
    isMilestone: false,
    isBlocked: true,
    blockedBy: "PRG-010 Piling mat construction",
    predecessors: ["PRG-010", "PRG-020"],
    successors: ["PRG-022", "PRG-030"],
    predecessorDetails: [
      { id: "PRG-010", name: "PRG-010 Piling mat construction", relation: "Finishes before this starts (FS)", statusColor: "emerald" },
      { id: "PRG-020", name: "PRG-020 Excavation to formation", relation: "Finishes before this starts (FS)", statusColor: "emerald" }
    ],
    successorDetails: [
      { id: "PRG-022", name: "PRG-022 Blinding concrete", relation: "Starts after this finishes (FS)", statusColor: "gray" },
      { id: "PRG-030", name: "PRG-030 Basement slab rebar", relation: "Starts after this finishes (FS)", statusColor: "red" }
    ],
    notes: "Blocked waiting on PRG-010 completion and mat load sign-off.",
    children: [],
    depth: 2,
    stage: "Groundworks",
    stageColumn: "Groundworks",
    float: -12,
  },
  {
    id: "PRG-022",
    wbs: "3.2.3",
    name: "Blinding concrete",
    level: "task",
    parentId: "wbs-3.2",
    status: "not-started",
    startDate: "2025-12-04",
    endDate: "2025-12-07",
    displayStart: "04 Dec 25",
    displayEnd: "07 Dec 25",
    duration: 3,
    progress: 0,
    trade: "Groundworks",
    costCode: "GW-03",
    assignee: "Michael O'Brien",
    assigneeInitials: "MO",
    description: "Pour 75mm blinding layer over compacted formation to provide clean working surface.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-021"],
    successors: ["PRG-023", "PRG-031"],
    predecessorDetails: [
      { id: "PRG-021", name: "PRG-021 Ground improvement", relation: "Finishes before this starts (FS)", statusColor: "red" }
    ],
    successorDetails: [
      { id: "PRG-023", name: "PRG-023 Formwork and pour", relation: "Starts after this finishes (FS)", statusColor: "gray" },
      { id: "PRG-031", name: "PRG-031 Basement slab pour", relation: "Starts after this finishes (FS)", statusColor: "gray" }
    ],
    notes: "Batch plant ready for delivery upon release.",
    children: [],
    depth: 2,
    stage: "Groundworks",
    stageColumn: "Groundworks",
    float: 4,
  },
  {
    id: "PRG-023",
    wbs: "3.2.4",
    name: "Formwork and pour",
    level: "task",
    parentId: "wbs-3.2",
    status: "not-started",
    startDate: "2025-12-08",
    endDate: "2025-12-14",
    displayStart: "08 Dec 25",
    displayEnd: "14 Dec 25",
    duration: 6,
    progress: 0,
    trade: "Groundworks",
    costCode: "GW-04",
    assignee: "Michael O'Brien",
    assigneeInitials: "MO",
    description: "Edge shuttering, starter bars and lift pit ground beam concrete pours.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-022"],
    successors: [],
    predecessorDetails: [
      { id: "PRG-022", name: "PRG-022 Blinding concrete", relation: "Finishes before this starts (FS)", statusColor: "gray" }
    ],
    notes: "Timber formwork fabricated in yard.",
    children: [],
    depth: 2,
    stage: "Groundworks",
    stageColumn: "Groundworks",
    float: 5,
  },

  // Stage: Foundations (6 tasks)
  {
    id: "PRG-030",
    wbs: "3.3.1",
    name: "Basement slab rebar",
    level: "task",
    parentId: "wbs-3.3",
    status: "blocked",
    startDate: "2025-12-05",
    endDate: "2025-12-13",
    displayStart: "05 Dec 25",
    displayEnd: "13 Dec 25",
    duration: 8,
    progress: 0,
    trade: "Foundations",
    costCode: "FND-01",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Install bottom reinforcement mesh, shear links, starter dowels and bar chairs for basement raft slab.",
    isCritical: true,
    isMilestone: false,
    isBlocked: true,
    blockedBy: "PRG-021 Ground improvement - vibro stone columns",
    predecessors: ["PRG-021"],
    successors: ["PRG-031"],
    predecessorDetails: [
      { id: "PRG-021", name: "PRG-021 Ground improvement", relation: "Finishes before this starts (FS)", statusColor: "red" }
    ],
    successorDetails: [
      { id: "PRG-031", name: "PRG-031 Basement slab pour", relation: "Starts after this finishes (FS)", statusColor: "gray" }
    ],
    notes: "Rebar steel delivery stored in holding bay.",
    children: [],
    depth: 2,
    stage: "Foundations",
    stageColumn: "Foundations",
    float: -8,
  },
  {
    id: "PRG-031",
    wbs: "3.3.2",
    name: "Basement slab pour",
    level: "task",
    parentId: "wbs-3.3",
    status: "not-started",
    startDate: "2025-12-14",
    endDate: "2025-12-17",
    displayStart: "14 Dec 25",
    displayEnd: "17 Dec 25",
    duration: 3,
    progress: 0,
    trade: "Foundations",
    costCode: "FND-02",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Major continuous concrete pour for 750m3 basement raft foundation with 2 mobile pumps.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["PRG-030", "PRG-022"],
    successors: ["PRG-032"],
    predecessorDetails: [
      { id: "PRG-030", name: "PRG-030 Basement slab rebar", relation: "Finishes before this starts (FS)", statusColor: "red" },
      { id: "PRG-022", name: "PRG-022 Blinding concrete", relation: "Finishes before this starts (FS)", statusColor: "gray" }
    ],
    successorDetails: [
      { id: "PRG-032", name: "PRG-032 Waterproofing", relation: "Starts after this finishes (FS)", statusColor: "gray" }
    ],
    notes: "Traffic management plan approved for weekend pour.",
    children: [],
    depth: 2,
    stage: "Foundations",
    stageColumn: "Foundations",
    float: 0,
  },
  {
    id: "PRG-032",
    wbs: "3.3.3",
    name: "Waterproofing",
    level: "task",
    parentId: "wbs-3.3",
    status: "not-started",
    startDate: "2025-12-18",
    endDate: "2025-12-23",
    displayStart: "18 Dec 25",
    displayEnd: "23 Dec 25",
    duration: 5,
    progress: 0,
    trade: "Foundations",
    costCode: "FND-03",
    assignee: "Sarah Chen",
    assigneeInitials: "SC",
    description: "Apply Type A barrier waterproofing membrane to perimeter toe and kicker joints.",
    isCritical: true,
    isMilestone: false,
    predecessors: ["PRG-031"],
    successors: [],
    predecessorDetails: [
      { id: "PRG-031", name: "PRG-031 Basement slab pour", relation: "Finishes before this starts (FS)", statusColor: "gray" }
    ],
    notes: "Waterproofing warranty inspection scheduled.",
    children: [],
    depth: 2,
    stage: "Foundations",
    stageColumn: "Foundations",
    float: 0,
  },
  {
    id: "PRG-040",
    wbs: "3.4.1",
    name: "Basement walls",
    level: "task",
    parentId: "wbs-3.4",
    status: "not-started",
    startDate: "2026-04-21",
    endDate: "2026-05-01",
    displayStart: "21 Apr 26",
    displayEnd: "01 May 26",
    duration: 10,
    progress: 0,
    trade: "Substructure",
    costCode: "BSM-01",
    assignee: "John Smith",
    assigneeInitials: "JS",
    description: "Formwork, reinforcement and single-sided pour of perimeter reinforced concrete retaining walls.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-030", "PRG-031"],
    successors: ["PRG-041"],
    predecessorDetails: [
      { id: "PRG-030", name: "PRG-030 Basement slab rebar", relation: "Finishes before this starts (FS)", statusColor: "red" },
      { id: "PRG-031", name: "PRG-031 Basement slab pour", relation: "Finishes before this starts (FS)", statusColor: "gray" }
    ],
    successorDetails: [
      { id: "PRG-041", name: "PRG-041 Backfill", relation: "Starts after this finishes (FS)", statusColor: "gray" }
    ],
    notes: "Coordinate waterbar placement with structural engineer.",
    children: [],
    depth: 2,
    stage: "Basement",
    stageColumn: "Basement",
    float: 4,
  },
  {
    id: "PRG-041",
    wbs: "3.4.2",
    name: "Backfill",
    level: "task",
    parentId: "wbs-3.4",
    status: "not-started",
    startDate: "2026-05-02",
    endDate: "2026-05-07",
    displayStart: "02 May 26",
    displayEnd: "07 May 26",
    duration: 5,
    progress: 0,
    trade: "Civils",
    costCode: "BSM-02",
    assignee: "Tom Harris",
    assigneeInitials: "TH",
    description: "Granular backfill compaction behind basement retaining walls in 300mm layers.",
    isCritical: false,
    isMilestone: false,
    predecessors: ["PRG-040"],
    successors: [],
    predecessorDetails: [
      { id: "PRG-040", name: "PRG-040 Basement walls", relation: "Finishes before this starts (FS)", statusColor: "gray" }
    ],
    notes: "Compaction testing to be carried out every 2 layers.",
    children: [],
    depth: 2,
    stage: "Basement",
    stageColumn: "Basement",
    float: 4,
  },
];

// WBS Navigation Structure definition
export interface WBSItem {
  id: string;
  name: string;
  count: number;
  isExpanded?: boolean;
  children?: WBSItem[];
}

export const WBS_STRUCTURE_TREE: WBSItem[] = [
  { id: "prelims", name: "1. Preliminaries", count: 8 },
  { id: "enabling", name: "2. Enabling Works", count: 12 },
  {
    id: "substructure",
    name: "3. Substructure",
    count: 24,
    isExpanded: true,
    children: [
      { id: "piling", name: "3.1 Piling", count: 6 },
      { id: "groundworks", name: "3.2 Groundworks", count: 8 },
      { id: "foundations", name: "3.3 Foundations", count: 6 },
      { id: "basement", name: "3.4 Basement", count: 4 },
    ],
  },
  { id: "superstructure", name: "4. Superstructure", count: 32 },
  { id: "facade", name: "5. Façade", count: 18 },
  { id: "fitout", name: "6. Fitout", count: 22 },
  { id: "completion", name: "7. Completion", count: 10 },
];

export const ALL_PROGRAMME_TASKS: ProgrammeTask[] = [
  ...INITIAL_PROGRAMME_TASKS,
  ...ATTENTION_TASKS,
  ...NETWORK_TASKS,
];

export function getProgrammeData(): ProgrammeData {
  return {
    ...PROGRAMME_DATA_INITIAL,
    tasks: ALL_PROGRAMME_TASKS,
    taskMap: new Map(ALL_PROGRAMME_TASKS.map((t) => [t.id, t])),
    phases: ALL_PROGRAMME_TASKS.filter((t) => t.level === "phase"),
    totalTasks: ALL_PROGRAMME_TASKS.length,
    completedTasks: ALL_PROGRAMME_TASKS.filter((t) => t.status === "complete").length,
    blockedTasks: ALL_PROGRAMME_TASKS.filter((t) => t.status === "blocked").length,
    avgProgress: 48,
    startDate: "2025-09-01",
    endDate: "2026-06-30",
  };
}

export function getVisibleTasks(
  dataOrTasks: ProgrammeData | ProgrammeTask[],
  expandedNodes: Set<string>,
  attentionFilter?: string,
  searchQuery?: string
): ProgrammeTask[] {
  const allTasks = Array.isArray(dataOrTasks) ? dataOrTasks : dataOrTasks.tasks;
  let tasks = allTasks;

  if (attentionFilter && attentionFilter !== "all") {
    if (attentionFilter === "overdue") {
      tasks = tasks.filter((t) => t.isOverdue || t.status === "blocked");
    } else if (attentionFilter === "blocked") {
      tasks = tasks.filter((t) => t.status === "blocked" || t.isBlocked);
    } else if (attentionFilter === "due-this-week") {
      tasks = tasks.filter((t) => t.isDueThisWeek);
    }
  }

  if (searchQuery && searchQuery.trim()) {
    const q = searchQuery.toLowerCase();
    tasks = tasks.filter(
      (t) =>
        t.name.toLowerCase().includes(q) ||
        t.id.toLowerCase().includes(q) ||
        t.wbs.toLowerCase().includes(q) ||
        (t.assignee && t.assignee.toLowerCase().includes(q))
    );
  }

  const result: ProgrammeTask[] = [];

  function addChildren(parentId: string | null) {
    const directChildren = tasks.filter((t) => t.parentId === parentId);
    for (const task of directChildren) {
      result.push(task);
      if (task.children.length > 0 && expandedNodes.has(task.id)) {
        addChildren(task.id);
      }
    }
  }

  const rootTasks = tasks.filter((t) => t.parentId === null);
  for (const root of rootTasks) {
    result.push(root);
    if (root.children.length > 0 && expandedNodes.has(root.id)) {
      addChildren(root.id);
    }
  }

  return result.length > 0 ? result : tasks.slice(0, 25);
}

